#!/usr/bin/env node
// Builds the deployable app from src/index.html:
//   - stamps the version from package.json (__VERSION__ = 20.0.0, __VERSION_SHORT__ = 20.0)
//   - pre-compiles the JSX block so phones no longer download/run Babel on every launch
//   - injects iOS launch-screen links
//   - writes index.html + sw.js (offline service worker: cache-first app shell, cache keyed by version)
// Usage: node build.js   (or npm run build). Edit src/index.html — never the generated index.html.
const fs = require('fs');
const path = require('path');
const Babel = require('@babel/standalone');

const ROOT = __dirname;
const pkg = JSON.parse(fs.readFileSync(path.join(ROOT, 'package.json'), 'utf8'));
const VERSION = pkg.version;
const VERSION_SHORT = VERSION.split('.').slice(0, 2).join('.');

let html = fs.readFileSync(path.join(ROOT, 'src/index.html'), 'utf8');
html = html.split('__VERSION_SHORT__').join(VERSION_SHORT).split('__VERSION__').join(VERSION);

// ---- compile JSX ----
const JSX_BLOCK = /<script type="text\/babel">([\s\S]*?)<\/script>/;
const match = html.match(JSX_BLOCK);
if (!match) throw new Error('src/index.html: no <script type="text/babel"> block found');
const compiled = Babel.transform(match[1], { presets: ['react'], sourceType: 'script', comments: false }).code;
new Function(compiled); // parse check: fail the build on a syntax error rather than ship a blank app
html = html.replace(JSX_BLOCK, () => `<script>\n${compiled}\n</script>`);

// ---- iOS launch screens ----
const iphones = JSON.parse(fs.readFileSync(path.join(ROOT, 'tools/iphones.json'), 'utf8'));
const splashLinks = iphones.map(([w, h, dpr]) => {
  const file = `splash/splash-${w * dpr}x${h * dpr}.png`;
  if (!fs.existsSync(path.join(ROOT, file))) throw new Error(`missing ${file} — run npm run assets`);
  return `<link rel="apple-touch-startup-image" media="screen and (device-width: ${w}px) and (device-height: ${h}px) and (-webkit-device-pixel-ratio: ${dpr}) and (orientation: portrait)" href="${file}">`;
}).join('\n');
if (!html.includes('<!--SPLASH-->')) throw new Error('src/index.html: missing <!--SPLASH--> marker');
html = html.replace('<!--SPLASH-->', () => splashLinks);

const banner = `<!-- GENERATED by build.js from src/index.html (v${VERSION}) — edit the source, then run: npm run build -->\n`;
fs.writeFileSync(path.join(ROOT, 'index.html'), banner + html);

// ---- service worker ----
const CORE = [
  './', './index.html', './manifest.webmanifest',
  './vendor/react.production.min.js', './vendor/react-dom.production.min.js',
  './icons/apple-touch-icon.png', './icons/icon-192.png', './icons/icon-512.png',
];
for (const f of CORE.slice(2)) if (!fs.existsSync(path.join(ROOT, f))) throw new Error(`service worker precache asset missing: ${f}`);
const sw = `// GENERATED by build.js (v${VERSION}) — do not edit.
// App shell is cache-first: launching never waits on the network, so weak gym signal can't hang it on a
// black screen. Every launch re-checks sw.js; a new version installs in the background (fresh copies via
// cache:'reload'), takes over, and the app offers a reload / applies it next launch.
const CACHE = 'ironclad-${VERSION}';
const CORE = ${JSON.stringify(CORE)};
const SCOPE = new URL(self.registration.scope).pathname;
self.addEventListener('install', e => {
  e.waitUntil(caches.open(CACHE)
    .then(c => c.addAll(CORE.map(u => new Request(u, { cache: 'reload' }))))
    .then(() => self.skipWaiting()));
});
self.addEventListener('activate', e => {
  e.waitUntil(caches.keys()
    .then(keys => Promise.all(keys.filter(k => k.startsWith('ironclad-') && k !== CACHE).map(k => caches.delete(k))))
    .then(() => self.clients.claim()));
});
self.addEventListener('fetch', e => {
  const req = e.request;
  if (req.method !== 'GET') return;
  const url = new URL(req.url);
  if (url.origin !== location.origin) return;
  if (req.mode === 'navigate') {
    // Only the app itself is served from the shell; any other page on the site goes to the network.
    if (url.pathname !== SCOPE && url.pathname !== SCOPE + 'index.html') return;
    e.respondWith(caches.open(CACHE).then(c => c.match('./index.html')).then(hit => hit || fetch(req)));
    return;
  }
  e.respondWith(caches.match(req).then(hit => hit || fetch(req).then(res => {
    if (res.ok && res.type === 'basic') { const copy = res.clone(); caches.open(CACHE).then(c => c.put(req, copy)); }
    return res;
  })));
});
`;
fs.writeFileSync(path.join(ROOT, 'sw.js'), sw);

const kb = (f) => (fs.statSync(path.join(ROOT, f)).size / 1024).toFixed(0) + ' KB';
console.log(`Built v${VERSION}: index.html ${kb('index.html')}, sw.js ${kb('sw.js')} (JSX pre-compiled, ${iphones.length} launch screens)`);
