// GENERATED by build.js (v20.0.0) — do not edit.
// App shell is cache-first: launching never waits on the network, so weak gym signal can't hang it on a
// black screen. Every launch re-checks sw.js; a new version installs in the background (fresh copies via
// cache:'reload'), takes over, and the app offers a reload / applies it next launch.
const CACHE = 'ironclad-20.0.0';
const CORE = ["./","./index.html","./manifest.webmanifest","./vendor/react.production.min.js","./vendor/react-dom.production.min.js","./icons/apple-touch-icon.png","./icons/icon-192.png","./icons/icon-512.png"];
const SCOPE = new URL(self.registration.scope).pathname;
self.addEventListener('install', e => {
  e.waitUntil(caches.open(CACHE)
    .then(c => c.addAll(CORE.map(u => new Request(u, { cache: 'reload' }))))
    .then(() => self.skipWaiting()));
});
self.addEventListener('activate', e => {
  e.waitUntil(caches.keys()
    .then(keys => Promise.all(keys.filter(k => k.startsWith('ironclad-') && k !== CACHE).map(k => caches.delete(k))))
    .then(() => self.clients.claim()));
});
self.addEventListener('fetch', e => {
  const req = e.request;
  if (req.method !== 'GET') return;
  const url = new URL(req.url);
  if (url.origin !== location.origin) return;
  if (req.mode === 'navigate') {
    // Only the app itself is served from the shell; any other page on the site goes to the network.
    if (url.pathname !== SCOPE && url.pathname !== SCOPE + 'index.html') return;
    e.respondWith(caches.open(CACHE).then(c => c.match('./index.html')).then(hit => hit || fetch(req)));
    return;
  }
  e.respondWith(caches.match(req).then(hit => hit || fetch(req).then(res => {
    if (res.ok && res.type === 'basic') { const copy = res.clone(); caches.open(CACHE).then(c => c.put(req, copy)); }
    return res;
  })));
});
